# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'llm_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11llm_service.proto\"\"\n\x10InferenceRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"#\n\x11InferenceResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2<\n\nLLMService\x12.\n\x05Infer\x12\x11.InferenceRequest\x1a\x12.InferenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEREQUEST']._serialized_start=21
  _globals['_INFERENCEREQUEST']._serialized_end=55
  _globals['_INFERENCERESPONSE']._serialized_start=57
  _globals['_INFERENCERESPONSE']._serialized_end=92
  _globals['_LLMSERVICE']._serialized_start=94
  _globals['_LLMSERVICE']._serialized_end=154
# @@protoc_insertion_point(module_scope)
